# Generated by Django 4.1.5 on 2023-01-05 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MoneyCategorys',
            },
        ),
        migrations.CreateModel(
            name='MoneyDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('income', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MoneyDayLogs',
            },
        ),
        migrations.CreateModel(
            name='MoneyDetailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('money_type', models.CharField(choices=[('0', '지출'), ('1', '수입')], default='0', max_length=10)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('share_url', models.CharField(max_length=128)),
                ('share_limit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail_logs', to='moneylogs.moneycategory')),
                ('day_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_logs', to='moneylogs.moneydaylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MoneyDetailLogs',
            },
        ),
    ]
