# Generated by Django 4.1.5 on 2023-01-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneylogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneydetaillog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail_logs', to='moneylogs.moneycategory'),
        ),
        migrations.AlterField(
            model_name='moneydetaillog',
            name='share_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
